export const List = [
  {
    id: 1,
    name: '김승기',
    className: '햇님반',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '100',
    weight: '15',
    address: '경기도 용인시 기흥구 어정로 12-34, 405동 1402호',
    parents: { father: '김동길', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-05',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '속이 안 좋아요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-05',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 2,
    name: '정의철',
    className: '햇님반',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-05',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-05',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 3,
    name: '양동민',
    className: '',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-06',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 4,
    name: '정형일',
    className: '달님반',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-06',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 5,
    name: '박지민',
    className: '',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-06',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 6,
    name: '김승기',
    className: '별님반',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-06',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 7,
    name: '정의철',
    className: '',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-06',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 8,
    name: '양동민',
    className: '햇님반',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-06',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 9,
    name: '정형일',
    className: '햇님반',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-06',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 10,
    name: '박지민',
    className: '달님반',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-06',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 11,
    name: '김승기',
    className: '햇님반',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-06',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 12,
    name: '정의철',
    className: '햇님반',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-05',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-05',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 13,
    name: '양동민',
    className: '',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-05',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-05',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 15,
    name: '박지민',
    className: '',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-05',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-05',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 5,
    name: '박지민',
    className: '',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-05',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-05',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
  {
    id: 16,
    name: '김승기',
    className: '별님반',
    createDate: '2025-06-13',
    role: 'child',
    birth: '2022-06-14',
    height: '120',
    weight: '25',
    address: '서울역',
    parents: { father: '정약용', mother: '최동순' },
    phone: { father: '010-1234-5678', mother: '010-9876-5432' },
    healthRecords: [
      {
        date: '2025-06-02',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-03',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '고열',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-04',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '머리가 아파요',
      },
      {
        date: '2025-06-05',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '구토',
        memo: '점심먹고 배가 아프다 했어요',
      },
      {
        date: '2025-06-06',
        temp: '37.5',
        height: '100',
        weight: '18',
        symptom: '기침',
        memo: '속이 안 좋아요',
      },
    ],
    medication: {
      name: '타이레놀 어린이시럽',
      dose: '5ml',
      time: '식후 30분',
      period: '6월22일~24일',
      purpose: '열,콧물',
      note: '열 없으면 투약 중단, 너무 거부하면 사탕이랑 같이',
    },
    vaccination: {
      BCG: '2026.12.22',
      schedule: '2025.06.25',
    },
    allergy: {
      items: '계란, 해산물, 채소',
      reaction: '호흡곤란, 두드러기',
      severity: '가벼움',
      note: '계란 알레르기가 심합니다. 유의 부탁드립니다.',
    },
    lifeRecords: [
      {
        date: '2025-06-05',
        meal: '잘먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '혼자 있음',
        memo: '적당한 수면이 필요해보여요',
      },
      {
        date: '2025-06-04',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '다들 있음',
        memo: '흐에',
      },
      {
        date: '2025-06-03',
        meal: '많이먹음',
        napTime: '13:00~14:00',
        play: '참여하지 않음',
        social: '친구들과 잘지냄',
        memo: '으아아아',
      },
      {
        date: '2025-06-02',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '점심 뭐먹죠',
      },
      {
        date: '2025-06-01',
        meal: '잘안먹음',
        napTime: '13:00~14:00',
        play: '참여함',
        social: '혼자 있음',
        memo: '테스트입니다.',
      },
    ],

    eatingHabit: {
      likes: ['딸기', '진미채', '미역국'],
      dislikes: ['김치', '브로콜리', '피망'],
      status: '적음',
      note: '식사량은 적지만 항상 식사에 적극적으로 참여',
    },

    socialRelation: {
      closeFriends: ['챗지피티'],
      favoritePlay: ['술래잡기', '블록 쌓기'],
      note: '다정다감하지만 상남자의 면모가 감춰져있음',
    },
  },
];
